language: node_js
node_js:
- '6.9.5'
branches:
  only:
  - master
before_install:
  - gem install sass
before_script:
- npm install -g grunt-cli
- npm install -g bower
- grunt gh-pages-clean
- bower update
env:
  global:
  - DOCBASE_TOKEN="1c63cff238d03f5bc190d6c61c6b98c38af6a9c2"
sudo: false
notifications:
  email: false
